#!/usr/bin/env bash
# Pull the live Project list from a running Jarvis server and write one
# SKILL.md under skills/projects/<slug>/ per non-archived project. Each
# generated skill bakes in the project's id, slug, name, and tags so
# Claude Code can route project-specific instructions ("start the next
# Approved requirement on <name>") to the right Jarvis row without the
# user having to remember any ids.
#
# Re-runs are idempotent: a skill marked as autogenerated (frontmatter
# `jarvis_autogen: true`) is rewritten in place, while orphaned files
# (projects that were archived or deleted on the server) are removed.
# Anything without the autogen marker is left untouched — operators
# can hand-edit a generated skill and add `jarvis_autogen: false` to
# pin it.
#
# Usage:
#   scripts/sync_projects.sh [--dry-run]
#
# Env: see scripts/jarvis_api.sh (JARVIS_BASE_URL, JARVIS_TOKEN).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=./jarvis_api.sh
source "${SCRIPT_DIR}/jarvis_api.sh"

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

PROJECTS_DIR="${PLUGIN_ROOT}/skills/projects"
mkdir -p "$PROJECTS_DIR"

# Fetch live projects (excludes archived rows by default).
projects_json="$(jarvis_get /v1/projects)"
slugs_seen=()

# jq filter: emit one TSV row per project — id <tab> slug <tab> name <tab> description <tab> tags-joined
rows="$(jq -r '
  if type == "array" then .
  elif .projects then .projects
  elif .items then .items
  else [.] end
  | .[]
  | [
      .id,
      .slug,
      .name,
      (.description // ""),
      ((.tags // []) | join(","))
    ]
  | @tsv
' <<<"$projects_json")"

if [[ -z "$rows" ]]; then
  printf 'jarvis-control: no projects returned from %s/v1/projects\n' "$JARVIS_BASE_URL" >&2
fi

while IFS=$'\t' read -r id slug name description tags; do
  [[ -z "$slug" ]] && continue
  slugs_seen+=("$slug")
  skill_dir="${PROJECTS_DIR}/${slug}"
  skill_file="${skill_dir}/SKILL.md"

  # Skip pinned (hand-edited) skills.
  if [[ -f "$skill_file" ]] && grep -q '^jarvis_autogen: false' "$skill_file"; then
    printf '  pinned   %s\n' "$slug"
    continue
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '  would write %s\n' "$skill_file"
    continue
  fi

  mkdir -p "$skill_dir"
  # Sanitise free-form fields so they sit safely inside YAML frontmatter:
  # collapse newlines, strip control chars, and escape backslashes / double
  # quotes for the YAML double-quoted scalars below.
  yaml_escape() {
    printf '%s' "$1" | tr '\n\r\t' '   ' | sed 's/\\/\\\\/g; s/"/\\"/g'
  }
  name_yaml="$(yaml_escape "$name")"
  desc_yaml="$(yaml_escape "$description")"
  # Keywords are YAML flow-sequence items — keep them to a safe charset.
  keyword_from() {
    printf '%s' "$1" | tr ',' ' ' | tr -cd 'A-Za-z0-9_ -' | tr ' ' '-' | sed 's/--*/-/g; s/^-//; s/-$//'
  }
  name_kw="$(keyword_from "$name")"
  tags_kw=""
  if [[ -n "$tags" ]]; then
    tags_kw=", $(printf '%s' "$tags" | tr ',' '\n' | while read -r t; do
      kw="$(keyword_from "$t")"
      [[ -n "$kw" ]] && printf '%s, ' "$kw"
    done)"
    tags_kw="${tags_kw%, }"
  fi

  cat >"$skill_file" <<EOF
---
name: jarvis-project-${slug}
description: "Operate the Jarvis Project ${name_yaml} (slug: ${slug}). Use when the user wants to inspect, start, approve, or review requirements scoped to ${name_yaml}. Hands off to the jarvis-runs skill for write actions but keeps project context locked in."
activation: both
keywords: [jarvis, project, ${slug}, ${name_kw}${tags_kw}]
version: "0.1.0"
jarvis_autogen: true
jarvis_project_id: "${id}"
jarvis_project_slug: "${slug}"
jarvis_project_name: "${name_yaml}"
jarvis_synced_at: "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
---

# Jarvis Project: ${name}

You are operating against the Jarvis Project with:

- **id**: \`${id}\`
- **slug**: \`${slug}\`
- **name**: ${name}
${description:+- **description**: ${description}}
${tags:+- **tags**: ${tags}}

This skill is **autogenerated** by \`scripts/sync_projects.sh\` from the
live \`/v1/projects\` listing. Hand-edits are preserved across re-sync
only if you change \`jarvis_autogen\` to \`false\` in the frontmatter.

## What you can do here

All operations talk to the configured Jarvis server
(\`\$JARVIS_BASE_URL\`, default \`http://localhost:7001\`). The
\`jarvis-runs\` skill owns the imperative verbs (start / approve /
reject / dispatch-review); this skill's job is to keep the project
context locked in so you never have to ask the user "which project?"
again.

Common asks and how to handle them:

| User asks                                  | Call                                                                              |
|--------------------------------------------|-----------------------------------------------------------------------------------|
| "show the board" / "list requirements"     | \`GET /v1/projects/${slug}/requirements?triage_state=approved\`                   |
| "what's in triage?"                        | \`GET /v1/projects/${slug}/requirements?triage_state=proposed\`                   |
| "start the next ready requirement"         | pick top Approved row with assignee + deps met → \`POST /v1/requirements/<id>/runs\` |
| "approve <title>"                          | resolve id from the list above → \`POST /v1/requirements/<id>/approve\`           |
| "reject <title> because <reason>"          | \`POST /v1/requirements/<id>/reject\` with \`{ "reason": "..." }\`                |
| "what's in Review?"                        | filter the requirements list by \`status = "review"\`                             |
| "ask the reviewer to verify <title>"       | \`POST /v1/requirements/<id>/review\` (requires Subagent acceptance policy)       |
| "what changed recently?"                   | \`GET /v1/requirements/<id>/activities\`                                          |
| "show the project memory"                  | \`GET /v1/projects/${slug}/memory\`                                               |

Use the helpers in \`scripts/jarvis_api.sh\`:

\`\`\`bash
source scripts/jarvis_api.sh
jarvis_get "/v1/projects/${slug}/requirements?triage_state=approved" | jq '.'
\`\`\`

## Guardrails

- **Never** approve / reject a triage row without the user's
  explicit go-ahead — those are human-judgement gates.
- Starting a run (\`POST .../runs\`) is approval-gated on the Jarvis
  side anyway, but echo the requirement title and id back to the user
  before firing the request.
- If the project's \`automation.auto_mode_enabled\` is false
  (\`GET /v1/projects/${slug}\` shows it), mention that the auto loop
  won't pick up new approved rows on its own — manual run dispatch is
  required.
EOF

  printf '  wrote    %s\n' "$skill_file"
done <<<"$rows"

# Prune orphans (autogen skills whose project no longer exists / is archived).
if [[ "$DRY_RUN" -eq 0 ]]; then
  shopt -s nullglob
  for dir in "${PROJECTS_DIR}"/*/; do
    slug="$(basename "$dir")"
    keep=0
    for seen in "${slugs_seen[@]:-}"; do
      if [[ "$seen" == "$slug" ]]; then
        keep=1
        break
      fi
    done
    if [[ "$keep" -eq 0 ]]; then
      if [[ -f "${dir}/SKILL.md" ]] && grep -q '^jarvis_autogen: true' "${dir}/SKILL.md"; then
        rm -rf "$dir"
        printf '  removed  %s\n' "$slug"
      else
        printf '  kept     %s (not autogen)\n' "$slug"
      fi
    fi
  done
fi

printf 'jarvis-control: synced %d project(s)\n' "${#slugs_seen[@]}"
